### ISSUE TITLE
Strange predictions

### ISSUE THREAD

**Issue by Rhywun** [MakeshVineeth/WikiPreview.Fluent.Plugin#11]
The predictions that appear in the list seem irrelevant until I type the entire word I'm looking for. See example below.

Scenario:
- Trigger the wiki plug in, start typing "mayonnaise"

Expected result:
- The list narrows down to "mayonnaise" after a few letters typed

Actual result:
- Irrelevant matches are shown (see attachment 1.png)
- Until I type the entire word (see attachment 2.png)

Similar happens with almost any search. Is this by design? Thanks!

![1](https://user-images.githubusercontent.com/1157174/204162460-c88341c3-77c3-4228-ace1-9c611ec30a70.png)

![2](https://user-images.githubusercontent.com/1157174/204162461-cf1a92bc-c600-4040-9c29-fb184faab499.png)

**Comment by MakeshVineeth** [comment]
Hello there! Sorry of the delayed response. This is actually by design, this plugin merely requests the Wikipedia API for results and display as is. So, when you typed "Mayonnais", there might be matches near to perfect as shown in the picture 1 according to Wikipedia. It doesn't necessarily have to be a title, the word can be found inside the description also. Nevertheless, I'll see what I can do from my side to improve this further :)

**Comment by Rhywun** [comment]
OK, if that's on Wikipedia's API then probably nothing you can do. OK to close.

Thanks
